name: Deploy Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build and Deploy
        run: |
          npm install -g mintlify
          cd docs && mintlify build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site
      - uses: actions/deploy-pages@v4
